# Generated by Django 4.0.4 on 2022-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails_only',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('date_of_ordering', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_ordering',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
